git clone https://github.com/MokaMokiMoke/Seafile
git clone https://github.com/MokaMokiMoke/BinaryClock
git clone https://github.com/MokaMokiMoke/FunWithShells
git clone https://github.com/MokaMokiMoke/HashBase
git clone https://github.com/MokaMokiMoke/RandomFileGenerator
git clone https://github.com/MokaMokiMoke/FloydWarshall
git clone https://github.com/MokaMokiMoke/Weihnachtsraetsel
git clone https://github.com/MokaMokiMoke/isFullPrimeRecursive
git clone https://github.com/MokaMokiMoke/BCryptTest
git clone https://github.com/MokaMokiMoke/BarGraphDrawer
git clone https://github.com/MokaMokiMoke/NetMonitor
git clone https://github.com/MokaMokiMoke/BigIntegerCalculator